# Generated by Django 4.2.1 on 2023-05-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actormodel',
            options={'verbose_name': 'Actor', 'verbose_name_plural': 'Actors'},
        ),
        migrations.AlterModelOptions(
            name='filmmodel',
            options={'verbose_name': 'Film', 'verbose_name_plural': 'Films'},
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='name',
            field=models.CharField(help_text='Please, add film name.', max_length=500),
        ),
    ]
