# Generated by Django 4.2.1 on 2023-06-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_commentmodel_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('films', models.ManyToManyField(related_name='film_categories', to='film.filmmodel')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
